# Generated by Django 4.2.7 on 2023-11-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='area',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='assunto',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='classe_processo',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='data_distribuicao',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='juiz',
            field=models.CharField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='process',
            name='valor_acao',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
