# Generated by Django 4.2.7 on 2023-12-02 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_process_area_process_assunto_process_classe_processo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
