# Generated by Django 4.2.7 on 2023-12-02 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_processo_delete_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='processo',
            name='data',
            field=models.JSONField(default={}),
        ),
    ]
